/**
 * Ambient module declarations for optional peer dependencies.
 * These packages are installed by consuming applications, not in the infra monorepo.
 */
declare module 'js-yaml';
declare module 'uuid';

/**
 * Minimal Prisma client stubs for enums used in utils.
 * Full types are generated by `prisma generate` in consuming apps.
 */
declare module '@prisma/client' {
  export const FileBucketVendor: {
    readonly s3: 's3';
    readonly oss: 'oss';
    readonly tos: 'tos';
    readonly gcs: 'gcs';
    readonly qiniu: 'qiniu';
    readonly us3: 'us3';
    readonly cos: 'cos';
  };
  export type FileBucketVendor = (typeof FileBucketVendor)[keyof typeof FileBucketVendor];

  export const FileEnvType: {
    readonly dev: 'dev';
    readonly test: 'test';
    readonly prod: 'prod';
    readonly produs: 'produs';
    readonly prodap: 'prodap';
  };
  export type FileEnvType = (typeof FileEnvType)[keyof typeof FileEnvType];

  export interface FileSource {
    id: string;
    vendor?: FileBucketVendor;
    bucket?: string;
    key?: string;
    ext?: string;
    env?: string;
    [key: string]: unknown;
  }
}
