import { z } from 'zod';

/**
 * Model info for LLM prompt
 */
export const LLMModelInfoSchema = z.object({
  modelId: z.string(),
  vendor: z.string(),
  providerKeyId: z.string(),
  capabilities: z.array(z.string()),
  healthScore: z.number().optional(),
  isPrimary: z.boolean().optional(),
});

export type LLMModelInfo = z.infer<typeof LLMModelInfoSchema>;

/**
 * Capability tag info for LLM prompt
 */
export const LLMCapabilityTagSchema = z.object({
  tagId: z.string(),
  name: z.string(),
  description: z.string().optional(),
  category: z.string(),
  priority: z.number(),
  requiredModels: z.array(z.string()).optional(),
});

export type LLMCapabilityTag = z.infer<typeof LLMCapabilityTagSchema>;

/**
 * Composite scenario for LLM prompt
 */
export const LLMCompositeScenarioSchema = z.object({
  name: z.string(),
  description: z.string().optional(),
  patterns: z.array(z.string()),
});

export type LLMCompositeScenario = z.infer<typeof LLMCompositeScenarioSchema>;

/**
 * Routing rule generated by LLM
 */
export const LLMRoutingRuleSchema = z.object({
  name: z.string(),
  description: z.string(),
  pattern: z.string(),
  matchType: z.enum(['keyword', 'regex', 'intent']),
  targetModel: z.string(),
  targetProviderKeyId: z.string(),
  confidence: z.number().min(0).max(100),
  reasoning: z.string(),
});

export type LLMRoutingRule = z.infer<typeof LLMRoutingRuleSchema>;

/**
 * Complete LLM response schema
 */
export const LLMRoutingResponseSchema = z.object({
  rules: z.array(LLMRoutingRuleSchema),
  defaultModel: z.string(),
  defaultProviderKeyId: z.string(),
  analysis: z.string(),
});

export type LLMRoutingResponse = z.infer<typeof LLMRoutingResponseSchema>;

/**
 * Options for routing generation
 */
export const RoutingGenerationOptionsSchema = z.object({
  customInstructions: z.string().optional(),
  modelPreference: z.enum(['balanced', 'performance', 'cost']).optional(),
});

export type RoutingGenerationOptions = z.infer<
  typeof RoutingGenerationOptionsSchema
>;
