/**
 * Minimal Prisma client stubs for shared-db package.
 * Full types are generated by `prisma generate` in consuming apps.
 */
declare module '@prisma/client' {
  export class PrismaClient {
    constructor(options?: Record<string, unknown>);
    $connect(): Promise<void>;
    $disconnect(): Promise<void>;
    $extends(extension: Record<string, unknown>): this;
    $transaction<T>(fn: (client: any) => Promise<T>, options?: { maxWait?: number; timeout?: number; isolationLevel?: string }): Promise<T>;
    [model: string]: any;
  }

  export namespace Prisma {
    export type TransactionIsolationLevel = string;
    export type SortOrder = 'asc' | 'desc';
    export type InputJsonValue = string | number | boolean | null | InputJsonValue[] | { [key: string]: InputJsonValue };
    export const dmmf: unknown;
    export class PrismaClientKnownRequestError extends Error {
      code: string;
      meta?: Record<string, unknown>;
    }
    export class PrismaClientValidationError extends Error {}
    export class PrismaClientInitializationError extends Error {
      errorCode?: string;
    }
    export class PrismaClientUnknownRequestError extends Error {}
    export class PrismaClientRustPanicError extends Error {}

    // CountryCode query types — permissive stubs
    export type CountryCodeWhereUniqueInput = Record<string, unknown>;
    export type CountryCodeWhereInput = Record<string, unknown>;
    export type CountryCodeOrderByWithRelationInput = Record<string, unknown>;
    export type CountryCodeSelect = Record<string, boolean | undefined>;
    export type CountryCodeCreateInput = Record<string, unknown>;
    export type CountryCodeUpdateInput = Record<string, unknown>;
  }

  export interface CountryCode {
    id: string;
    continent?: string | null;
    [key: string]: unknown;
  }
}
