// Stub type declarations for @prisma/client generated output (.prisma/client/default).
// The actual model types are generated by `prisma generate` in consuming apps --
// this file provides minimal stubs so infra packages compile without a database
// or prisma schema in this repo.

declare module '.prisma/client/default' {
  // ============================================================================
  // Enums -- Prisma generates const-object + type-alias, not TypeScript enums
  // ============================================================================

  export const FileBucketVendor: {
    readonly s3: 's3';
    readonly oss: 'oss';
    readonly tos: 'tos';
    readonly gcs: 'gcs';
    readonly qiniu: 'qiniu';
    readonly us3: 'us3';
    readonly cos: 'cos';
  };
  export type FileBucketVendor = (typeof FileBucketVendor)[keyof typeof FileBucketVendor];

  export interface FileSource {
    id: string;
    vendor?: FileBucketVendor;
    bucket?: string;
    key?: string;
    ext?: string;
    env?: string;
    [key: string]: unknown;
  }

  export const FileEnvType: {
    readonly dev: 'dev';
    readonly test: 'test';
    readonly prod: 'prod';
    readonly produs: 'produs';
    readonly prodap: 'prodap';
  };
  export type FileEnvType = (typeof FileEnvType)[keyof typeof FileEnvType];

  export const VideoQuality: {
    readonly VIDEO_360P: 'VIDEO_360P';
    readonly VIDEO_720P: 'VIDEO_720P';
    readonly VIDEO_1080P: 'VIDEO_1080P';
    readonly VIDEO_4K: 'VIDEO_4K';
    readonly VIDEO_ORIGIN: 'VIDEO_ORIGIN';
  };
  export type VideoQuality = (typeof VideoQuality)[keyof typeof VideoQuality];

  // ============================================================================
  // Model types -- minimal stubs with index signatures for flexibility
  // ============================================================================

  export interface VideoInfo {
    id: string;
    width?: number | null;
    height?: number | null;
    duration?: number | null;
    streamDuration?: number | null;
    sar?: string | null;
    dar?: string | null;
    rFrameRate?: string | null;
    spriteCount?: number | null;
    ffmpegInfo?: any;
    [key: string]: unknown;
  }

  export interface AudioInfo {
    id: string;
    duration?: number | null;
    streamDuration?: number | null;
    channels?: number | null;
    channelLayout?: string | null;
    sampleRate?: string | null;
    bitRate?: number | null;
    ffmpegInfo?: any;
    [key: string]: unknown;
  }

  export interface ImageInfo {
    id: string;
    width?: number | null;
    height?: number | null;
    sar?: string | null;
    dar?: string | null;
    ffmpegInfo?: any;
    [key: string]: unknown;
  }

  export interface UserInfo {
    id: string;
    email: string;
    nickname?: string | null;
    name?: string | null;
    [key: string]: unknown;
  }

  export interface CountryCode {
    id: string;
    continent?: string | null;
    [key: string]: unknown;
  }

  export interface MobileAuth {
    id: string;
    mobile?: string | null;
    [key: string]: unknown;
  }

  // ============================================================================
  // Prisma namespace
  // ============================================================================

  export namespace Prisma {
    export type TransactionIsolationLevel =
      | 'ReadUncommitted'
      | 'ReadCommitted'
      | 'RepeatableRead'
      | 'Serializable';

    export type SortOrder = 'asc' | 'desc';

    export type InputJsonValue = string | number | boolean | null | InputJsonValue[] | { [key: string]: InputJsonValue };

    export interface TransactionClient {
      [model: string]: ModelDelegate;
    }

    // eslint-disable-next-line @typescript-eslint/no-empty-interface
    export interface NullTypes {}

    export const dmmf: unknown;
    export const validator: unknown;

    export function getExtensionContext(client: unknown): unknown;

    // Model-specific query types
    export type CountryCodeWhereUniqueInput = Record<string, unknown>;
    export type CountryCodeWhereInput = Record<string, unknown>;
    export type CountryCodeOrderByWithRelationInput = Record<string, unknown>;
    export type CountryCodeSelect = Record<string, boolean | undefined>;
    export type CountryCodeCreateInput = Record<string, unknown>;
    export type CountryCodeUpdateInput = Record<string, unknown>;

    // Error classes
    export class PrismaClientKnownRequestError extends Error {
      code: string;
      meta?: Record<string, unknown>;
    }

    export class PrismaClientValidationError extends Error {}

    export class PrismaClientInitializationError extends Error {
      errorCode?: string;
    }

    export class PrismaClientUnknownRequestError extends Error {}

    export class PrismaClientRustPanicError extends Error {}
  }

  // ============================================================================
  // Model delegate -- permissive type so findMany/create/update etc. compile
  // ============================================================================

  export type ModelDelegate = Record<string, (...args: any[]) => any>;

  // ============================================================================
  // PrismaClient
  // ============================================================================

  export class PrismaClient {
    constructor(options?: Record<string, unknown>);
    $connect(): Promise<void>;
    $disconnect(): Promise<void>;
    $on(eventType: string, callback: (event: unknown) => void): void;
    $extends(extension: Record<string, unknown>): this;
    $transaction<T>(fn: (client: Prisma.TransactionClient) => Promise<T>): Promise<T>;
    $transaction<T>(
      fn: (client: Prisma.TransactionClient) => Promise<T>,
      options?: { isolationLevel?: Prisma.TransactionIsolationLevel; maxWait?: number; timeout?: number },
    ): Promise<T>;

    // Model delegates -- use index signature so any model name compiles
    [model: string]: ModelDelegate;
  }

  export type PrismaClientOptions = Record<string, unknown>;
}

// Re-export from @prisma/client so that imports from '@prisma/client' resolve
declare module '@prisma/client' {
  export * from '.prisma/client/default';
}
